bfat/urls.py
from django.conf.urls import url

from . import views

app_name = 'bfat'

urlpatterns = [
    url(r'^$', views.bfat_view, name='bfat_view'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^stats/corp/$', views.stats_corp, name='stats_corp'),
    url(r'^stats/corp/(?P<corpid>[0-9]+)/$', views.stats_corp, name='stats_corp'),
    url(r'^stats/corp/(?P<corpid>[0-9]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$', views.stats_corp, name='stats_corp'),
    url(r'^stats/char/$', views.stats_char, name='stats_char'),
    url(r'^stats/char/(?P<charid>[0-9]+)/$', views.stats_char, name='stats_char'),
    url(r'^stats/char/(?P<charid>[0-9]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$', views.stats_char, name='stats_char'),
    url(r'^stats/ally/$', views.stats_alliance, name='stats_ally'),
    url(r'^stats/ally/(?P<allianceid>[0-9]+)/$', views.stats_alliance, name='stats_ally'),
    url(r'^stats/ally/(?P<allianceid>[0-9]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$', views.stats_alliance, name='stats_ally'),
    url(r'^links/$', views.links, name='links'),
    url(r'^links/create/esi/$', views.link_create_esi, name='link_create_esi'),
    url(r'^links/create/click/$', views.link_create_click, name='link_create_click'),
    url(r'^links/add/$', views.link_add, name='link_add'),
    url(r'^links/edit/$', views.edit_link, name="link_edit"),
    url(r'^links/(?P<hash>[a-zA-Z0-9]+)/edit/$', views.edit_link, name="link_edit"),
    url(r'^links/(?P<hash>[a-zA-Z0-9]+)/click/$', views.click_link, name="link_click"),
    url(r'^links/del/$', views.del_link, name="link_delete"),
    url(r'^links/(?P<hash>[a-zA-Z0-9]+)/del/$', views.del_link, name="link_delete"),
    url(r'^links/(?P<hash>[a-zA-Z0-9]+)/(?P<fat>[0-9]+)/del/$', views.del_fat, name="fat_delete"),
]

bfat/models.py
from django.db import models
from django.contrib.auth.models import User
from allianceauth.eveonline.models import EveCharacter
from django.utils import timezone

# Create your models here.


def get_sentinel_user():
    return User.objects.get_or_create(username='deleted')[0]


# FatLink Model
class FatLink(models.Model):
    fattime = models.DateTimeField(default=timezone.now)
    fleet = models.CharField(max_length=254, null=True)
    hash = models.CharField(max_length=254)
    creator = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))

    def __str__(self):
        return self.hash[6:]

    class Meta:
        permissions = (('manage_bfat', 'Can manage the bFAT module'),
                       ('stats_corp_own', 'Can see own corp stats'),
                       ('stats_corp_other', 'Can see stats of other corps.'),
                       ('stats_char_other', 'Can see stats of characters not associated with current user.'))


# Clickable Link Duration Model
class ClickFatDuration(models.Model):
    duration = models.PositiveIntegerField()
    fleet = models.ForeignKey(FatLink, on_delete=models.CASCADE)


# PAP/FAT Model
class Fat(models.Model):
    character = models.ForeignKey(EveCharacter, on_delete=models.CASCADE)
    fatlink = models.ForeignKey(FatLink, on_delete=models.CASCADE)
    system = models.CharField(max_length=100, null=True)
    shiptype = models.CharField(max_length=100, null=True)

    class Meta:
        unique_together = (('character', 'fatlink'),)

    def __str__(self):
        return "{} - {}".format(self.fatlink, self.character)


# Log Model for Manual FAT creation
class ManualFat(models.Model):
    creator = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))
    fatlink = models.ForeignKey(FatLink, on_delete=models.CASCADE)
    character = models.ForeignKey(EveCharacter, on_delete=models.CASCADE)
    
    # Add property for getting the user for a character.

    def __str__(self):
        return "{} - {} ({})".format(self.fatlink, self.character, self.creator)


# Log Model for Deletion of Fats and FatLinks
class DelLog(models.Model):
    # 0 for FatLink, 1 for Fat
    deltype = models.BooleanField(default=0)
    remover = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))
    string = models.CharField(max_length=100)

    def delt_to_str(self):
        if self.deltype == 0:
            return 'FatLink'
        else:
            return 'Fat'

    def __str__(self):
        return '{}/{} - {}'.format(self.delt_to_str(), self.string, self.remover)

bfat/templates/bfat/addlink.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{% trans 'Fleet Activity' %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include "bfat/menu.html" %}
        <h2>{% trans "Create a " %}{{ term }}{% trans "Link" %}</h2>
        {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    {% if msg.0 != 'warning' %}<h4>{% if msg.0 == 'danger' %}Oh No!{% elif msg.0 == 'success' %}Success!{% endif %}</h4>{% endif %}
                    <p>{{ msg.1 }}</p>
                </div>
        {% endif %}
        <div class="row">
            <div class="col-md-6 mr-md-1">
                <h3> Create a {{ term }}Link using ESI. </h3>
                <p> If you are not in a fleet, you <i>can</i> still use this option, however you will <i>need</i> to use a flat list if you do.</p>
                <a class="btn btn-primary btn-block" href="{% url 'bfat:link_create_esi' %}"><span class="fa fa-plus fa-fw"></span>Add {{ term }}Link from ESI</a>
            </div>
            <div class="col-md-6 ml-md-2">
                <h3> Create a clickable {{ term }}Link</h3>
                <p>This option will create a clickable like just like that created by the standard FAT module.</p>
                <!-- Form Goes Here -->
                <form class="form" role="form" action="{% url 'bfat:link_create_click' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <input type="text" class="form-control" name="name" id="name" placeholder="Fleet Name" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <input type="number" class="form-control" name="duration" id="duration" placeholder="Live Time (Minutes)" required>
                            </div>
                            <div class="col-md-6">
                                <button class="btn btn-primary btn-block" type="submit" name="submit_click" id="submit_click"><span class="fa fa-plus fa-fw"></span>Add Clickable {{ term }}Link</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

bfat/templates/bfat/bfatview.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{% trans 'Fleet Activity' %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include "bfat/menu.html" %}
        <h2>{% trans "Recent" %}</h2>
        {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    {% if msg.0 != 'warning' %}<h4>{% if msg.0 == 'danger' %}Oh No!{% elif msg.0 == 'success' %}Success!{% endif %}</h4>{% endif %}
                    <p>{{ msg.1 }}</p>
                </div>
        {% endif %}
        <ul class="nav nav-tabs">
             <li class="active"><a data-toggle="tab" href="#fats">{{ term }}s</a></li>
            <li><a data-toggle="tab" href="#fatlinks">{{ term }}{% trans "Links" %}</a></li>
        </ul>
        <div class="tab-content">
            <div id="fats" class="tab-pane fade in active panel-default">
                <div class="panel-body">
                    <h4> Your Most Recent {{ term }}s </h4>
                    <ul class="nav nav-pills">
                        {% for char in fats %}
                            {% if forloop.first %}
                                <li class="active"><a data-toggle="tab" href="#{{ char|last }}"><img class="img-circle" src="https://imageserver.eveonline.com/Character/{{ char|last }}_32.jpg"/>  {{ char.0 }}</a></li>
                            {% else %}
                                <li><a data-toggle="tab" href="#{{ char|last }}"><img class="img-circle" src="https://imageserver.eveonline.com/Character/{{ char|last }}_32.jpg"/>  {{ char.0 }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                    <div class="tab-content">
                        {% for char in fats %}
                            {% if forloop.first %}
                                <div id="{{ char|last }}" class="tab-pane fade in active panel-default">
                            {% else %}
                                <div id="{{ char|last }}" class="tab-pane fade active panel-default">
                            {% endif %}
                            <div class="panel-body">
                            {% if char|slice:"1:-1"|length > 0 %}
                                <table class="table">
                                    <thead>
                                        <th>Fleet Name</th>
                                        <th>Location</th>
                                        <th>Ship</th>
                                        <th>EVE Time</th>
                                    </thead>
                                    <tbody>
                                        {% for fat in char|slice:"1:" %}
                                            <tr>
                                                <td>{% if fat.fatlink.fleet %}{{ fat.fatlink.fleet }}{% else %}{{ fat.fatlink.hash }}{% endif %}</td>
                                                <td>{{ fat.system }}</td>
                                                <td>{{ fat.shiptype }}</td>
                                                <td>{{ fat.fatlink.fattime }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <div class="alert alert-warning" role="alert">
                                    <p>No {{ term }}s for {{ char.0 }}</p>
                                </div>
                            {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div id="fatlinks" class="tab-panel fade active panel-default">
                <div class="panel-body">
                    <h4> Most Recent {{ term }} Links (limit 10)</h4>
                    <table class="table">
                        <thead>
                            <th>Fleet Name</th>
                            <th>Creator</th>
                            <th>EVE Time</th>
                            <th>Utils</th>
                        </thead>
                        <tbody>
                            {% for link in links %}
                                <tr>
                                    <td>{% if link.fleet %}{{ link.fleet }}{% else %}{{ link.hash }}{% endif %}</td>
                                    <td>{{ link.creator.profile.main_character.character_name }}</td>
                                    <td>{{ link.fattime }}</td>
                                    <td>{% if perms.bfat.edit_fatlink %}<a class="btn btn-info" href="{% url 'bfat:link_edit' link.hash %}"><span class="glyphicon glyphicon-pencil"></span></a>{% endif %}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>


{% endblock %}

bfat/templates/bfat/date_select.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load filters %}
{% block page_title %}{{ corporation }} {% trans "Fleet Activity" %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include "bfat/menu.html" %}
        <h2>{{ corporation }} {% trans "Fleet Activity" %}</h2>
        <h4>Only months with {{ term }} data in the last 12 months are shown.</h4>

        <table class="table">
            <thead>
                <th>Month</th>
                <th>{{ term }}s</th>
                <th></th>
            </thead>
            <tbody>
                {% for month in months %}
                    <tr>
                        <td>{{ month.0|month }}</td>
                        <td>{{ month.1 }}</td>
                        <td><a href="/bfat/stats/{% if type == 0 %}corp{% elif type == 1 %}ally{% endif %}/{% if corporation == 'No Alliance' %}000{% else %}{{ corpid }}{% endif %}/{{ month.0 }}/{{ year }}/" class="btn btn-primary"><span class="glyphicon glyphicon-eye-open"></span></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

bfat/templates/bfat/fat_list.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{% trans 'Fleet Activity' %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include "bfat/menu.html" %}
        <h2>{% trans "All" %} {{ term }}{% trans "Links" %}</h2>
        <table class="table" id="link-list">
            <thead>
                <th>Fleet Name</th>
                <th>Creator</th>
                <th>EVE Time</th>
                <th># of {{ term }}s</th>
                <th>Utils</th>
            </thead>
            <tbody>
                {% for link in links %}
                    <tr>
                        <td>{% if link.fleet %}{{ link.fleet }}{% else %}{{ link.hash }}{% endif %}</td>
                        <td>{{ link.creator.profile.main_character.character_name }}</td>
                        <td>{{ link.fattime }}</td>
                        <td>{{ link.number_of_fats }}</td>
                        <td>{% if perms.bfat.change_fatlink %}<a class="btn btn-info" href="{% url 'bfat:link_edit' link.hash %}"><span class="glyphicon glyphicon-pencil"></span></a>{% endif %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}
{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.js" integrity="sha256-l6SU+rVSlkyIcMsqjy0mb6ne/qPpYotdVSFd9vLmV1A=" crossorigin="anonymous"></script>
{% endblock %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
{% endblock %}
{% block extra_script %}
    $.fn.dataTable.moment = function ( format, locale ) {
        var types = $.fn.dataTable.ext.type;

        // Add type detection
        types.detect.unshift( function ( d ) {
            return moment( d, format, locale, true ).isValid() ?
                'moment-'+format :
                null;
        } );

        // Add sorting method - use an integer for the sorting
        types.order[ 'moment-'+format+'-pre' ] = function ( d ) {
            return moment( d, format, locale, true ).unix();
        };
    };

    $(document).ready(function(){
        $.fn.dataTable.moment( 'MMM. D, YYYY, hh:mm a' );

        $('#link-list').DataTable();
    });
{% endblock %}

bfat/templates/bfat/fleet_edit.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load bootstrap %}
{% block page_title %}{% trans 'Fleet Activity' %}{% endblock %}

{% block content %}
        <div class="col-lg-12">
            <br>
            {% include "bfat/menu.html" %}
            {% if msg == 200 %}
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    <h4>Success!</h4>
                    <p>&#9642; {{ term }}Link Created!</p>
                    <p>&#9642; {{ term }}s have been queued, they may take a few mins to show up.</p>
                    <p>&#9642; Make sure to set the fleet name!</p>
                </div>
            {% elif msg == 403 %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    <h4>Not Fleet Boss!</h4>
                    <p>&#9642; {{ term }}Link created. Please upload a flatlist using the flatlist tab to generate {{ term }}s for fleet members.</p>
                    <p>&#9642; Make sure to set the fleet name!</p>
                </div>
            {% elif msg == 404 %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    <h4>Not in Fleet!</h4>
                    <p>&#9642; {{ term }}Link created. The character used to create this {{ term }}Link is not in a fleet. In order to generate {{ term }}s for fleet members, please upload a flatlist using the flatlist tab.</p>
                    <p>&#9642; Make sure to set the fleet name!</p>
                </div>
            {% elif msg == 0 %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">&times</span>
                </button>
                <h4>Oh No!</h4>
                <p>Something went wrong!</p>
            </div>
            {% elif msg == 202 %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">&times</span>
                </button>
                <h4>Success!</h4>
                <p>&#9642; Clickable {{ term }}Link Created!</p>
                <p>&#9642; Make sure to give your fleet members the following link to click so that they get credit for this fleet. </p>
                <p>&#9642; <i>Link: <a href="{% url 'bfat:link_click' link.hash %}" class="label label-success">COPY ME!</a></i> </p>
                </div>
            {% elif msg == 1 %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">&times</span>
                </button>
                <h4>Success!</h4>
                <p>Fleet name successfully changed.</p>
            </div>
            {% elif msg == 2 %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">&times</span>
                </button>
                <h4>Success!</h4>
                <p>&#9642; {{ term }}s successfully queued from flatlist.</p>
                <p>&#9642; {{ term }}s may take a few mins to show up.</p>
            </div>
            {% elif msg == 3 %}
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    <h4>Success!</h4>
                    <p>Manual {{ term }} processed.</p>
                </div>
            {% elif msg == 4 %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    <h4>Oh No!</h4>
                    <p>Manual {{ term }} processing failed! The character name you entered was not found.</p>
                </div>
            {% endif %}
            {% if debug %}
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    <p>{{ debug }}</p>
                </div>
            {% endif %}
            <h2>{% trans "Edit" %} {{ term }}{% trans "Link" %}</h2>
                <div class="col-md-12">
                    <div class="row">
                        <form class="form" role="form" action="" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Name" name="fleet" id="fleet" {% if link.fleet %}value="{{ link.fleet }}" {% endif %}>
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary" type="submit" name="set_name">Set Name</button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="col-md-2">Creator: {{ link.creator.profile.main_character.character_name }}</div>
                        <div class="col-md-2 col-md-offset-8">Time: {{ link.fattime }}</div>
                    </div>
                </div>
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" class="tab" href="#{{ term }}s">{{ term }}s</a></li>
                <li><a data-toggle="tab" class="tab" href="#flatlist">Flat List</a></li>
                <li><a data-toggle="tab" class="tab" href="#manualfat">Manual {{ term }}</a></li>
            </ul>
            <div class="tab-content">
                <div id="{{ term }}s" class="tab-pane fade in active panel-default">
                    <div class="panel-body">
                         <h4>{{ term }}s for this {{ term }}Link</h4>
                         <table class="table" id="fat-chars">
                             <thead>
                                <th>Character</th>
                                <th>Location</th>
                                <th>Ship Type</th>
                                <th>Utilities</th>
                             </thead>
                             <tbody>
                                {% for fat in fats %}
                                    <tr>
                                        <td>{{ fat.character.character_name }}</td>
                                        <td>{{ fat.system }}</td>
                                        <td>{{ fat.shiptype }}</td>
                                        <td>{% if perms.bfat.delete_fat %}<a class="btn btn-danger" href="{% url 'bfat:fat_delete' link.hash fat.id %}"><span class="glyphicon glyphicon-remove"></span></a>{% endif %}</td>
                                    </tr>
                                {% endfor %}
                             </tbody>
                         </table>
                    </div>
                </div>
                <div id="flatlist" class="tab-pane fade in panel-default">
                    <div class="panel-body">
                        <h4>Flat List Input</h4>
                        <p> Please keep in mind that processing flat lists may take a few minutes.</p>
                        {% if fats|length == 0 %}
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <textarea class="form-control" name="flatlist" rows="10" id="flatlist" required></textarea>
                            </div>
                            <br />
                            <button class="btn btn-primary btn-block" type="submit" name="submit_flatlist">Submit Flat List</button>
                        </form>
                        {% else %}
                        <form class="form-signin" role="form">
                            <div class="form-group">
                                <textarea class="form-control" name="flatlist" rows="10" id="flatlist" readonly>{{ flatlist }}</textarea>
                            </div>
                            <br />
                            <button class="btn btn-primary btn-block disabled" type="button">Submit Flat List</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
                <div id="manualfat" class="tab-pane fade in panel-default">
                    <div class="panel-body">
                        <h4>Manual {{ term }}</h4>
                        <p> Is someone missing from the list of {{ term }}s? Use this form to add them.
                        <br />
                        <strong>Note:</strong> This action is logged!</p>
                        <form class="form" role="form" action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" id="character_name" name="character" placeholder="Character Name" required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" id="location" name="system" placeholder="System">
                                    </div>
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" id="shiptype" name="shiptype" placeholder="Ship Type">
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-primary btn-block" type="submit" name="manual_fat">Add Manual {{ term }}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}
{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
{% endblock %}
{% block extra_script %}
    $(document).ready(function(){
        $('#fat-chars').DataTable();
    });
{% endblock %}

bfat/templates/bfat/menu.html
{% load staticfiles %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
<div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">{% trans "Toggle navigation" %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'bfat:bfat_view' %}">{% trans "Better FAT" %}</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="{% navactive request 'bfat_stats bfat_corp_stats bfat_char_stats bfat_ally_stats' %}">
                <a href="{% url 'bfat:stats' %}">{% trans "Statistics" %}</a>
            </li>
            <li class="{% navactive request 'bfat:links bfat:link_edit' %}">
                <a href="{% url 'bfat:links' %}">{{ term }} {% trans "Links" %}</a>
            </li>
            {% if perms.bfat.manage_bfat or perms.bfat.add_fatlink %}
                <li class="{% navactive request 'bfat:link_add' %}">
                    <a href="{% url 'bfat:link_add' %}">Add {{ term }}Link</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>